// import styles
import 'src/styles/main.scss'

// install service-worker
if ('serviceWorker' in navigator) {
  // register service-worker generated by sw-precache
  navigator.serviceWorker.register('/service-worker.js').catch((ex) => {
    console.warn(ex) // eslint-disable-line
  })
}

// install jquery
window.jQuery = window.$ = require('jquery')
// require('velocity-animate')
require('materialize-css/js/jquery.easing.1.3')
require('materialize-css/js/animation')
require('materialize-css/js/velocity.min')
require('materialize-css/js/global')
require('materialize-css/js/scrollspy')
